name: Build_macos_editor_3

on:
  push:
    # paths:
    #   - '**.js'
  schedule:
    - cron: '0 0 27 * *'

jobs:
  macos_build:
    name: macOS Build
    runs-on: "macos-13"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Build"
        shell: bash
        run: |
          bash build_3.sh
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ env.version }}
          path: "godot/Godot.tgz"
          retention-days: 3
