name: Build_macos_editor_4

on:
  push:
    paths:
      - '**.js'
  # schedule:
  #   - cron: '0 0 * * 0'

jobs:
  macos_build:
    name: macOS Build
    runs-on: "macos-latest"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Build"
        shell: bash
        run: |
          brew update
          brew install emscripten scons yasm
          git clone --depth 1 --branch 4.2 --recursive https://github.com/godotengine/godot
          cd godot
          echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          sh misc/scripts/install_vulkan_sdk_macos.sh
          git clone --depth 1 --recursive https://github.com/felipenune/godot_dragonbones modules/godot_dragonbones
          git clone --depth 1 --recursive https://github.com/Geequlim/ECMAScript modules/javascript
          scons platform=macos arch=x86_64 target=editor
          cp -r misc/dist/macos_tools.app ./Godot.app
          mkdir -p Godot.app/Contents/MacOS
          cp bin/godot.macos* Godot.app/Contents/MacOS/Godot
          chmod +x Godot.app/Contents/MacOS/Godot
          codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - Godot.app
          scons platform=web target=template_release
          scons platform=web target=template_debug
          bash ../build_4.sh
          bsdtar -czf Godot.tgz Godot.app bin/*.zip bin/*.apk
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: macos-${{ env.version }}
          path: "godot/Godot.tgz"
