name: Build_macos_editor_3

on:
  push:
    # paths:
    #   - '**.js'
  # schedule:
  #   - cron: '0 0 * * 0'

jobs:
  macos_build:
    name: macOS Build
    runs-on: "macos-latest"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Build"
        shell: bash
        run: |
          brew update
          brew install emscripten scons yasm
          git clone --depth 1 --branch 3.5 --recursive https://github.com/godotengine/godot
          cd godot
          echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          git clone --depth 1 --recursive https://github.com/mauville-technologies/godot_dragonbones modules/godot_dragonbones
          git clone --depth 1 --branch 3.4 --recursive https://github.com/Geequlim/ECMAScript modules/ECMAScript
          git clone --depth 1 --branch godot-3.x --recursive https://github.com/quinnvoker/qurobullet modules/qurobullet
          git apply modules/godot_dragonbones/build/android-no-rtti-patch.patch
          git apply modules/godot_dragonbones/build/js-no-rtti-patch.patch
          git apply --directory modules/godot_dragonbones ../1.patch
          scons platform=osx arch=x86_64 target=release_debug tools=yes
          cp -r misc/dist/osx_tools.app Godot.app
          mkdir -p Godot.app/Contents/MacOS
          cp bin/godot.osx* Godot.app/Contents/MacOS/Godot
          chmod +x Godot.app/Contents/MacOS/Godot
          scons platform=javascript tools=no target=release LINKFLAGS='-sGL_ENABLE_GET_PROC_ADDRESS'
          # https://github.com/Geequlim/ECMAScript/issues/57
          # scons platform=javascript tools=no target=release_debug LINKFLAGS='-sGL_ENABLE_GET_PROC_ADDRESS'
          bash ../build_3.sh
          bsdtar -czf Godot.tgz Godot.app bin/*.zip bin/*.apk
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: macos-${{ env.version }}
          path: "godot/Godot.tgz"
