name: Build_macos_editor_4

on:
  push:
    paths:
      - '**.js'
  schedule:
    - cron: '30 4 * * *'

jobs:
  macos_build:
    name: macOS Build
    runs-on: "macos-13"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Setup emsdk"
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.64
          no-cache: true
      - name: "Build"
        shell: bash
        run: |
          bash build_4.sh
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ env.version }}
          path: "godot/Godot.tgz"
          retention-days: 3
