name: Build

on:
  push:
  # schedule:
  #   - cron: '0 0 * * 0'

jobs:
  macos_build:
    name: macOS Build
    runs-on: "macos-latest"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: Install Scons
        run: python3 -m pip install -U scons
      - name: "Build"
        shell: bash
        run: |
          git clone --depth 1 --branch 4.1 --recursive https://github.com/godotengine/godot
          cd godot
          echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          git clone --depth 1 --recursive https://github.com/felipenune/godot_dragonbones modules/godot_dragonbones
          git clone --depth 1 --branch 4.1 --recursive https://github.com/Geequlim/ECMAScript modules/ECMAScript
          scons platform=macos arch=x86_64 target=editor warnings=extra werror=yes module_text_server_fb_enabled=yes
          cp -r misc/dist/osx_tools.app ./Godot.app
          mkdir -p Godot.app/Contents/MacOS
          cp bin/godot* Godot.app/Contents/MacOS/Godot
          chmod +x Godot.app/Contents/MacOS/Godot
          codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - Godot.app
          bsdtar -czf Godot.tgz Godot.app
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: macos-${{ env.version }}
          path: "godot/Godot.tgz"
  # macos_build:
  #   name: macOS Build
  #   runs-on: "macos-latest"
  #   steps:
  #     - name: "checkout repo"
  #       uses: actions/checkout@v4
  #     - name: Install Scons
  #       run: python3 -m pip install -U scons
  #     - name: "Build"
  #       shell: bash
  #       run: |
  #         git clone --depth 1 --branch 3.5 --recursive https://github.com/godotengine/godot
  #         cd godot
  #         echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
  #         git clone --depth 1 --recursive https://github.com/mauville-technologies/godot_dragonbones modules/godot_dragonbones
  #         git clone --depth 1 --branch 3.4 --recursive https://github.com/Geequlim/ECMAScript modules/ECMAScript
  #         scons platform=osx arch=x86_64 target=release_debug tools=yes
  #         cp -r misc/dist/osx_tools.app ./Godot.app
  #         mkdir -p Godot.app/Contents/MacOS
  #         cp bin/godot* Godot.app/Contents/MacOS/Godot
  #         chmod +x Godot.app/Contents/MacOS/Godot
  #         bsdtar -czf Godot.tgz Godot.app
  #     - name: "Upload artifact"
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: macos-${{ env.version }}
  #         path: "godot/Godot.tgz"
