name: Build_macos_editor_3

on:
  push:
  # schedule:
  #   - cron: '0 0 * * 0'

jobs:
  macos_build:
    name: macOS Build
    runs-on: "macos-latest"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Build"
        shell: bash
        run: |
          brew install emscripten scons
          git clone --depth 1 --branch 4.1 --recursive https://github.com/godotengine/godot
          cd godot
          echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          sh misc/scripts/install_vulkan_sdk_macos.sh
          git clone --depth 1 --recursive https://github.com/felipenune/godot_dragonbones modules/godot_dragonbones
          git clone --depth 1 --recursive https://github.com/Geequlim/ECMAScript modules/javascript
          # scons platform=macos arch=x86_64 target=editor
          cp -r misc/dist/macos_tools.app ./Godot.app
          # mkdir -p Godot.app/Contents/MacOS
          # cp bin/godot.macos* Godot.app/Contents/MacOS/Godot
          # chmod +x Godot.app/Contents/MacOS/Godot
          # codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - Godot.app
          scons platform=web target=template_release
          bsdtar -czf Godot.tgz Godot.app bin/godot.web*
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: macos-${{ env.version }}
          path: "godot/Godot.tgz"
  # macos_build:
  #   name: macOS Build
  #   runs-on: "macos-latest"
  #   steps:
  #     - name: "checkout repo"
  #       uses: actions/checkout@v4
  #     - name: "Build"
  #       shell: bash
  #       run: |
  #         brew install emscripten scons
  #         git clone --depth 1 --branch 3.5 --recursive https://github.com/godotengine/godot
  #         cd godot
  #         echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
  #         git clone --depth 1 --recursive https://github.com/mauville-technologies/godot_dragonbones modules/godot_dragonbones
  #         git clone --depth 1 --branch 3.4 --recursive https://github.com/Geequlim/ECMAScript modules/ECMAScript
  #         git apply ./modules/godot_dragonbones/build/android-no-rtti-patch.patch
  #         git apply ./modules/godot_dragonbones/build/js-no-rtti-patch.patch
  #         git apply --directory modules/godot_dragonbones ../1.patch
  #         scons platform=osx arch=x86_64 target=release_debug tools=yes
  #         cp -r misc/dist/osx_tools.app ./Godot.app
  #         mkdir -p Godot.app/Contents/MacOS
  #         cp bin/godot.osx* Godot.app/Contents/MacOS/Godot
  #         chmod +x Godot.app/Contents/MacOS/Godot
  #         scons platform=javascript tools=no target=release threads_enabled=no LINKFLAGS='-sGL_ENABLE_GET_PROC_ADDRESS'
  #         bsdtar -czf Godot.tgz Godot.app bin/godot.javascript*
  #     - name: "Upload artifact"
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: macos-${{ env.version }}
  #         path: "godot/Godot.tgz"
